name: Test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run jq and sponge
        run: |
          sudo apt-get update
          sudo apt-get install -y moreutils
          cat foo.json
          jq 'del(.b) foo.json | sponge foo.json'
          cat foo.json
