name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  run-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
            echo "This is the main branch"
          else
            echo "This is not the main branch"
          fi
