name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  run-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test" $GITHUB_REF
