name: Test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  run-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test script
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MESSAGE"
          echo "Secret: $SECRET_SUPER_SECRET"
          if echo $COMMIT_MESSAGE | grep "^edr-[0-9]\+\.[0-9]\+\.[0-9]\+-"; then
            echo "Publish pre-release"
          elif echo $COMMIT_MESSAGE | grep "^edr-[0-9]\+\.[0-9]\+\.[0-9]\+\s*"; then
            if [ "$GITHUB_REF" == "refs/heads/main" ]; then
              echo "Publish release"
            else
              echo "Release commit in non-main branch"
              exit 1
            fi
          fi
        env:
          SECRET_SUPER_SECRET: ${{ secrets.SECRET_SUPER_SECRET }}
