name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  run-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test script
        run: |
          if git log -1 --pretty=%B | grep "^edr-[0-9]\+\.[0-9]\+\.[0-9]\+-"; then
            echo "Publish pre-release"
          elif git log -1 --pretty=%B | grep "^edr-[0-9]\+\.[0-9]\+\.[0-9]\+\s*"; then
            if [ "$GITHUB_REF" == "refs/heads/main" ]; then
              echo "Publish release"
            else
              echo "Release commit in non-main branch"
              exit 1
            fi
          fi
