name: Test

env:
  ARR: ("foo" "bar" "baz)

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    matrix:
      settings:
        - a: 1
        - a: 2
        - a: 3
    steps:
      - name: Run
        run: |
          echo ${#ARR[@]}
          echo ${{ strategy.job-index }}
          echo ${{ strategy.job-total }}
