name: Test

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: |
          echo "Sleeping for 60 seconds"
          sleep 60
          echo "Done"
