name: Test

env:
  COUNT: 3

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        settings:
          - a: 1
          - a: 2
          - a: 3
    steps:
      - name: Run
        shell: bash
        run: |
          echo ${COUNT}
          echo ${{ strategy.job-index }}
          test ${{ strategy.job-total }} -eq ${COUNT}
